AWSTemplateFormatVersion: 2010-09-09
Conditions:
  IsCorsDefined:
    Fn::Not:
    - Fn::Equals:
      - Ref: CorsOrigin
      - ''
Outputs:
  ApiUrl:
    Description: The URL of the API Gateway you should invoke to send an email
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send
Parameters:
  CorsOrigin:
    Default: ''
    Description: (Optional) Cross-origin resource sharing (CORS) Origin. You can specify
      a single origin, all "*" or leave empty and no CORS will be applied.
    MaxLength: 250
    Type: String
  FromEmail:
    ConstraintDescription: Required. Must be a SES verified email address.
    Default: your@email.com
    Description: (Required) Represents the email sender. Must be a SES verified email.
      If you attempt to send email using a non-verified address or domain, the operation
      results in an "Email address not verified" error. Minimum 4 characters.
    MaxLength: 70
    MinLength: 4
    Type: String
Resources:
  LambdaEmailer:
    Properties:
      CodeUri: s3://app-repo-components/53ce4949e4e12296e47bb6c5634abf82
      Environment:
        Variables:
          CORS_ORIGIN:
            Ref: CorsOrigin
          FROM_EMAIL:
            Ref: FromEmail
      Events:
        EmailApi:
          Properties:
            Method: POST
            Path: /send
          Type: Api
        EmailOptionsApi:
          Properties:
            Method: OPTIONS
            Path: /send
          Type: Api
      Handler: index.handler
      Policies:
      - SESCrudPolicy:
          IdentityName:
            Ref: FromEmail
      Runtime: nodejs12.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
